"use client";

import { ArrowLeft, CaretLeft, CaretRight } from "@phosphor-icons/react";
import { AnimatePresence, motion, useReducedMotion } from "framer-motion";
import { useState } from "react";
import { stageArtwork } from "../../data/journey";
import { MemoryImage } from "../memories/MemoryImage";
import { MemoryVideo } from "../memories/MemoryVideo";
import { StageVideoPlayer } from "../memories/StageVideoPlayer";

type StageProps = { onReturnToMap: () => void; onComplete: () => void };
type BookPageId = "tet" | "journeys" | "video" | "pin";
type BookPage = { id: BookPageId; eyebrow: string; title: string; photos?: number[] };

const bookPages: BookPage[] = [
  { id: "tet", eyebrow: "Trang 01 - 02", title: "Album Tết", photos: [1, 2, 3, 4, 5, 6, 7, 8] },
  { id: "journeys", eyebrow: "Trang 03 - 04", title: "Những chuyến đi", photos: [9, 10, 11, 12, 13, 14, 15, 16] },
  { id: "video", eyebrow: "Trang 05", title: "Ánh đèn đầu năm" },
  { id: "pin", eyebrow: "Trang cuối", title: "Dấu ghim còn lại" },
];

const stageSixRuntimeStyles = String.raw`
.tet-codebook-scene .tet-code-cover-stage{position:absolute!important;z-index:10!important;inset:0!important;display:grid!important;place-items:center!important;padding-top:2rem!important}
.tet-codebook-scene .tet-code-cover-stage header{position:absolute!important;z-index:2!important;top:clamp(5rem,10vh,7.2rem)!important;left:50%!important;width:min(520px,88vw)!important;color:#fff9ed!important;text-align:center!important;text-shadow:0 3px 20px rgba(36,7,12,.78)!important;transform:translateX(-50%)!important}
.tet-codebook-scene .tet-code-cover-stage h1{margin:.3rem 0 .45rem!important;font-family:var(--font-display),Georgia,serif!important;font-size:clamp(2.6rem,5vw,4.6rem)!important;font-weight:600!important;letter-spacing:-.06em!important;line-height:.96!important}
.tet-codebook-scene .tet-code-cover-stage header>p:last-child{margin:0 auto!important;color:#fff5e5!important;font-size:1rem!important;font-weight:600!important;line-height:1.55!important}
.tet-codebook-scene .tet-code-cover{position:relative!important;display:block!important;width:min(370px,58vw)!important;aspect-ratio:.72!important;overflow:hidden!important;border:12px solid #4a1d27!important;border-radius:16px 20px 22px 15px!important;padding:0!important;background:radial-gradient(circle at 30% 18%,rgba(255,214,157,.15),transparent 19%),linear-gradient(125deg,#a74a55,#682531 43%,#41131e 100%)!important;box-shadow:-14px 13px 0 #38131d,0 28px 46px rgba(27,5,10,.58),inset 0 0 0 2px rgba(240,190,111,.45),inset 0 0 0 13px rgba(255,237,194,.1)!important;color:#ffe9b8!important;cursor:pointer!important;transform:translateY(9%)!important}
.tet-codebook-scene .tet-code-cover:before{position:absolute!important;inset:19px!important;border:1px solid rgba(246,205,130,.6)!important;border-radius:6px!important;content:""!important}
.tet-codebook-scene .tet-code-cover-ribbon{position:absolute!important;top:-8%!important;left:50%!important;width:66px!important;height:116%!important;border-right:1px solid rgba(255,233,177,.45)!important;border-left:1px solid rgba(255,233,177,.45)!important;background:linear-gradient(90deg,rgba(214,170,95,.18),rgba(255,218,132,.65),rgba(180,124,52,.25))!important;box-shadow:0 0 23px rgba(255,218,137,.25)!important;transform:translateX(-50%)!important}
.tet-codebook-scene .tet-code-cover-ornament{position:absolute!important;top:31%!important;left:50%!important;display:grid!important;width:74px!important;height:74px!important;place-items:center!important;border:1px solid rgba(255,225,151,.82)!important;border-radius:50%!important;background:rgba(94,29,39,.68)!important;box-shadow:0 0 0 8px rgba(253,209,127,.1),0 0 24px rgba(247,203,117,.4)!important;color:#ffe9b7!important;font-size:2rem!important;transform:translateX(-50%)!important}
.tet-codebook-scene .tet-code-cover strong,.tet-codebook-scene .tet-code-cover small{position:absolute!important;z-index:2!important;right:12%!important;left:12%!important;display:block!important;text-align:center!important;text-shadow:0 2px 10px rgba(42,8,14,.75)!important}
.tet-codebook-scene .tet-code-cover strong{bottom:22%!important;font-family:var(--font-display),Georgia,serif!important;font-size:clamp(1.25rem,2.1vw,1.6rem)!important;font-weight:600!important}.tet-codebook-scene .tet-code-cover small{bottom:13%!important;font-family:var(--font-body),sans-serif!important;font-size:.69rem!important;font-weight:800!important;letter-spacing:.1em!important;text-transform:uppercase!important}
.tet-codebook-scene .tet-code-reader{position:absolute!important;z-index:10!important;inset:0!important;perspective:1800px!important}.tet-codebook-scene .tet-code-reader-heading{position:absolute!important;z-index:12!important;top:clamp(5rem,9vh,7.2rem)!important;left:50%!important;width:min(600px,86vw)!important;color:#fff8eb!important;text-align:center!important;text-shadow:0 3px 20px rgba(39,7,14,.8)!important;transform:translateX(-50%)!important}.tet-codebook-scene .tet-code-reader-heading h1{margin:0!important;font-family:var(--font-display),Georgia,serif!important;font-size:clamp(1.7rem,3.2vw,2.9rem)!important;font-weight:600!important;letter-spacing:-.05em!important}.tet-codebook-scene .tet-code-reader-heading p{margin:0 0 .3rem!important;color:#ffd6a6!important;font-size:.68rem!important;font-weight:850!important;letter-spacing:.13em!important;text-transform:uppercase!important}
.tet-codebook-scene .tet-code-page-turn{position:absolute!important;top:clamp(10.4rem,20vh,12.7rem)!important;left:50%!important;width:min(1120px,88vw)!important;height:min(570px,61vh)!important;transform:translateX(-50%)!important}.tet-codebook-scene .tet-code-spread{position:relative!important;display:grid!important;grid-template-columns:minmax(0,1fr) 36px minmax(0,1fr)!important;width:100%!important;height:100%!important;overflow:hidden!important;border:12px solid #54232a!important;border-radius:16px 19px 20px 16px!important;background:linear-gradient(90deg,#5b252e,#9b4d52 48%,#56232c)!important;box-shadow:-11px 13px 0 #39161d,0 28px 47px rgba(27,5,10,.55),inset 0 0 0 1px rgba(255,216,144,.36)!important}.tet-codebook-scene .tet-code-paper{position:relative!important;overflow:hidden!important;padding:clamp(1rem,2vw,1.7rem)!important;background:repeating-linear-gradient(0deg,rgba(117,71,52,.07) 0 1px,transparent 1px 28px),linear-gradient(135deg,#f9efdf,#ead0a7)!important;box-shadow:inset -16px 0 25px rgba(106,56,47,.18)!important}.tet-codebook-scene .tet-code-paper-right{box-shadow:inset 16px 0 25px rgba(106,56,47,.18)!important}.tet-codebook-scene .tet-code-spine{display:grid!important;align-content:space-around!important;justify-items:center!important;padding:.6rem 0!important;background:linear-gradient(90deg,#442028,#c58a69 50%,#4a2029)!important}.tet-codebook-scene .tet-code-spine i{display:block!important;width:22px!important;height:9px!important;border:2px solid #5a2b2d!important;border-radius:999px!important;background:linear-gradient(#d2ad71,#9a623e)!important}
.tet-codebook-scene .tet-code-paper-kicker{margin-bottom:.7rem!important;color:#a0524c!important;font-size:clamp(.58rem,.8vw,.72rem)!important;font-weight:850!important;letter-spacing:.11em!important;text-transform:uppercase!important}.tet-codebook-scene .tet-code-photo-grid{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;grid-template-rows:repeat(2,minmax(0,1fr))!important;gap:clamp(.7rem,1.4vw,1.15rem)!important;height:calc(100% - 2rem)!important}.tet-codebook-scene .tet-code-photo-card{position:relative!important;display:block!important;width:100%!important;height:100%!important;overflow:visible!important;border:7px solid #fffaf0!important;border-radius:2px!important;padding:0!important;background:#fffaf0!important;box-shadow:0 9px 15px rgba(76,35,28,.34)!important;cursor:zoom-in!important}.tet-codebook-scene .tet-code-photo-card>.memory-image{display:block!important;width:100%!important;height:100%!important;overflow:hidden!important;background:#c9a583!important}.tet-codebook-scene .tet-code-photo-card .memory-image img{object-fit:cover!important}.tet-codebook-scene .tet-code-photo-card>span:last-child{position:absolute!important;z-index:3!important;top:-8px!important;left:50%!important;width:36%!important;height:13px!important;background:rgba(227,171,131,.82)!important;transform:translateX(-50%) rotate(-2deg)!important}
.tet-codebook-scene .tet-code-film-frame{position:relative!important;height:calc(100% - 3.3rem)!important;overflow:hidden!important;border:10px solid #f8ead2!important;border-radius:4px!important;background:#302128!important;box-shadow:0 11px 19px rgba(64,26,25,.38)!important}.tet-codebook-scene .tet-code-film-frame .memory-video{display:block!important;width:100%!important;height:100%!important;object-fit:cover!important}.tet-codebook-scene .tet-code-letter-page{padding:clamp(1.5rem,4vw,3.7rem)!important;color:#664037!important}.tet-codebook-scene .tet-code-letter-page h2{margin:.15rem 0 .8rem!important;color:#5c3734!important;font-family:var(--font-display),Georgia,serif!important;font-size:clamp(1.4rem,2.4vw,2.35rem)!important;font-weight:600!important;line-height:1.05!important}.tet-codebook-scene .tet-code-letter-page>p:not(.tet-code-paper-kicker){color:#795249!important;font-size:clamp(.78rem,1.1vw,.98rem)!important;font-weight:600!important;line-height:1.68!important}.tet-codebook-scene .tet-code-pin-page{display:grid!important;place-items:center!important}.tet-codebook-scene .tet-code-pin-button{display:grid!important;justify-items:center!important;gap:.5rem!important;border:0!important;padding:1.2rem 1.4rem!important;background:transparent!important;color:#693c3b!important;cursor:pointer!important;font-family:var(--font-display),Georgia,serif!important}.tet-codebook-scene .tet-code-pin-seal{display:grid!important;width:clamp(70px,8vw,104px)!important;height:clamp(70px,8vw,104px)!important;place-items:center!important;border:7px solid #b44d56!important;border-radius:50%!important;background:radial-gradient(circle,#cf6167,#89323e 72%)!important;box-shadow:0 8px 0 #753039,0 15px 23px rgba(74,29,25,.31)!important}.tet-codebook-scene .tet-code-pin-seal i{display:block!important;width:8px!important;height:28px!important;border-radius:8px!important;background:#f7d497!important;transform:rotate(42deg)!important}.tet-codebook-scene .tet-code-pin-button strong{font-size:clamp(1.2rem,1.8vw,1.55rem)!important}.tet-codebook-scene .tet-code-pin-button small{color:#936056!important;font-family:var(--font-body),sans-serif!important;font-size:.7rem!important;font-weight:800!important}
.tet-codebook-scene .tet-code-reader-controls{position:absolute!important;z-index:14!important;bottom:clamp(1rem,3.4vh,2.4rem)!important;left:50%!important;display:flex!important;align-items:center!important;gap:.9rem!important;color:#ffefd2!important;font-size:.75rem!important;font-weight:800!important;transform:translateX(-50%)!important}.tet-codebook-scene .tet-code-reader-controls button{display:inline-flex!important;align-items:center!important;gap:.25rem!important;border:1px solid rgba(255,227,179,.45)!important;border-radius:999px!important;padding:.48rem .82rem!important;background:rgba(74,20,29,.65)!important;color:#fff6e7!important;cursor:pointer!important;font-size:.72rem!important;font-weight:800!important}
@media(max-width:560px){.tet-codebook-scene .tet-code-cover-stage header{top:4.8rem!important}.tet-codebook-scene .tet-code-cover{width:min(270px,68vw)!important}.tet-codebook-scene .tet-code-reader-heading{top:4.8rem!important}.tet-codebook-scene .tet-code-page-turn{top:17.2vh!important;width:97vw!important;height:min(430px,52vh)!important}.tet-codebook-scene .tet-code-spread{grid-template-columns:minmax(0,1fr) 16px minmax(0,1fr)!important;border-width:5px!important}.tet-codebook-scene .tet-code-paper{padding:.36rem!important}.tet-codebook-scene .tet-code-paper-kicker{display:none!important}.tet-codebook-scene .tet-code-photo-grid{gap:.22rem!important;height:100%!important}.tet-codebook-scene .tet-code-photo-card{border-width:2px!important}.tet-codebook-scene .tet-code-film-frame{height:calc(100% - 1.4rem)!important;border-width:2px!important}.tet-codebook-scene .tet-code-letter-page{padding:.5rem!important}.tet-codebook-scene .tet-code-letter-page h2{font-size:.7rem!important}.tet-codebook-scene .tet-code-letter-page>p:not(.tet-code-paper-kicker){font-size:.48rem!important;line-height:1.32!important}.tet-codebook-scene .tet-code-pin-seal{width:38px!important;height:38px!important;border-width:4px!important}.tet-codebook-scene .tet-code-reader-controls{bottom:.7rem!important;gap:.34rem!important}.tet-codebook-scene .tet-code-reader-controls button{padding:.31rem .45rem!important;font-size:.56rem!important}}
`;
const roads = [
  { id: "understood", title: "Chỉ muốn được hiểu", description: "Có những lúc cả hai chỉ mong đối phương nghe mình thêm một chút. Đã cãi vã đã giận hờn tất cả chỉ để muốn vun đắp một tình yêu thật bình yên " },
  { id: "understand", title: "Học cách hiểu nhau", description: "Chậm hơn, khó hơn, nhưng là vẫn là cách để mình để mình đi tiếp sửa đổi sao cho pù hợp vs nhau. chấp nhận phàn không hoàn hảo của đối phương" },
];

function PhotoPreview({ photo, onClose }: { photo: number; onClose: () => void }) {
  return <motion.div className="tet-code-photo-preview" initial={{ opacity: 0, scale: 0.96 }} animate={{ opacity: 1, scale: 1 }} exit={{ opacity: 0, scale: 0.98 }} transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}><button type="button" onClick={onClose}>Quay lại trang sổ</button><MemoryImage stage={6} photo={photo} alt={`Kỷ niệm số ${photo}`} sizes="(max-width: 767px) 90vw, 900px" priority /></motion.div>;
}

function PhotoCard({ photo, index, onSelect }: { photo: number; index: number; onSelect: (photo: number) => void }) {
  return <motion.button type="button" className={`tet-code-photo-card card-${index + 1}`} onClick={() => onSelect(photo)} aria-label={`Xem lớn ảnh kỷ niệm ${index + 1}`} initial={{ opacity: 0, y: 18, rotate: index % 2 ? 2 : -2 }} animate={{ opacity: 1, y: 0, rotate: index % 2 ? 1.2 : -1.1 }} transition={{ delay: 0.11 + index * 0.055, duration: 0.46, ease: [0.22, 1, 0.36, 1] }}><MemoryImage stage={6} photo={photo} alt={`Kỷ niệm ${index + 1}`} sizes="(max-width: 767px) 20vw, 185px" priority={index < 4} /><span aria-hidden="true" /></motion.button>;
}

function PhotoSpread({ page, onSelect }: { page: BookPage; onSelect: (photo: number) => void }) {
  const photos = page.photos ?? [];
  return <div className="tet-code-spread tet-code-photo-spread"><section className="tet-code-paper tet-code-paper-left"><div className="tet-code-paper-kicker">{page.id === "tet" ? "Những ngày đầu năm" : "Từ những con đường đã đi"}</div><div className="tet-code-photo-grid">{photos.slice(0, 4).map((photo, index) => <PhotoCard key={photo} photo={photo} index={index} onSelect={onSelect} />)}</div></section><div className="tet-code-spine" aria-hidden="true"><i /><i /><i /><i /><i /></div><section className="tet-code-paper tet-code-paper-right"><div className="tet-code-paper-kicker">{page.id === "tet" ? "Cùng nhau giữ lại" : "Càng đi càng gần"}</div><div className="tet-code-photo-grid">{photos.slice(4, 8).map((photo, index) => <PhotoCard key={photo} photo={photo} index={index + 4} onSelect={onSelect} />)}</div></section></div>;
}

function VideoSpread() {
  return <div className="tet-code-spread tet-code-video-spread"><section className="tet-code-paper tet-code-paper-left"><div className="tet-code-film-frame"><MemoryVideo stage={6} /></div><p className="tet-code-film-caption">Một đoạn phim để nghe lại tiếng cười của hai đứa.</p></section><div className="tet-code-spine" aria-hidden="true"><i /><i /><i /><i /><i /></div><section className="tet-code-paper tet-code-paper-right tet-code-letter-page"><p className="tet-code-paper-kicker">Đèn lồng</p><h2>Một đoạn phim ở giữa những ngày đầu năm.</h2><p>Có những khoảnh khắc không cần kể lại, chỉ cần bấm phát là mọi cảm giác quay về.</p><span className="tet-code-pressed-flower" aria-hidden="true" /></section></div>;
}

function PinSpread({ onOpen }: { onOpen: () => void }) {
  return <div className="tet-code-spread tet-code-pin-spread"><section className="tet-code-paper tet-code-paper-left tet-code-pin-page"><button type="button" className="tet-code-pin-button" onClick={onOpen}><span className="tet-code-pin-seal" aria-hidden="true"><i /></span><strong>Dấu ghim</strong><small>Chạm để mở trang cuối</small></button></section><div className="tet-code-spine" aria-hidden="true"><i /><i /><i /><i /><i /></div><section className="tet-code-paper tet-code-paper-right tet-code-letter-page"><p className="tet-code-paper-kicker">Điều muốn nói</p><h2>Có một điều cuối cùng anh muốn hỏi em.</h2><p>Dù có những ngày vui, vẫn có những điều cần cả hai cùng lắng nghe.</p><span className="tet-code-ink-line" aria-hidden="true" /><span className="tet-code-pressed-flower" aria-hidden="true" /></section></div>;
}

export function StageSixTetJourney({ onReturnToMap, onComplete }: StageProps) {
  const [isBookOpen, setIsBookOpen] = useState(false);
  const [pageIndex, setPageIndex] = useState(0);
  const [selectedPhoto, setSelectedPhoto] = useState<number | null>(null);
  const [isDecisionVisible, setIsDecisionVisible] = useState(false);
  const [chosenRoad, setChosenRoad] = useState<string | null>(null);
  const reduceMotion = useReducedMotion();
  const currentPage = bookPages[pageIndex] ?? bookPages[0];
  const chosenRoadData = roads.find((road) => road.id === chosenRoad);

  function nextPage() { setPageIndex((current) => Math.min(bookPages.length - 1, current + 1)); }
  function previousPage() { setPageIndex((current) => Math.max(0, current - 1)); }

  return (
    <><style>{stageSixRuntimeStyles}</style>
    <section className={`tet-scene tet-codebook-scene${isBookOpen ? " is-book-open" : ""}${isDecisionVisible ? " is-decision" : ""}${chosenRoad ? " is-chosen" : ""}`} aria-label="Cuốn sổ kỷ niệm mùa xuân">
      <div className="tet-sky" aria-hidden="true" /><div className="tet-blossoms" aria-hidden="true">{Array.from({ length: 14 }, (_, index) => <span key={index} style={{ "--i": index } as React.CSSProperties} />)}</div>
      {isDecisionVisible && <div className="tet-decision-video" aria-label="Video kỷ niệm trước câu hỏi"><StageVideoPlayer loop poster={stageArtwork[6]} source="/memories/stage-6/decision-video.mp4">Trình duyệt này không hỗ trợ phát video.</StageVideoPlayer><span className="tet-decision-video-wash" aria-hidden="true" /></div>}
      <div className="scene-grain" aria-hidden="true" /><div className="scene-vignette" aria-hidden="true" />
      <button type="button" className="scene-back" onClick={onReturnToMap}><ArrowLeft size={16} weight="bold" />Quay lại bản đồ</button>

      {!isBookOpen && !isDecisionVisible && <motion.section className="tet-code-cover-stage" initial={reduceMotion ? false : { opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.72, ease: [0.22, 1, 0.36, 1] }}><header><p className="scene-eyebrow">Tết và chuyến đi mới</p><h1>Cuốn sổ của hai đứa</h1><p>Những ngày đầu năm, những chuyến đi và một điều còn lại.</p></header><motion.button type="button" className="tet-code-cover" onClick={() => setIsBookOpen(true)} whileHover={reduceMotion ? undefined : { y: -8, rotate: -0.5 }} whileTap={{ scale: 0.985 }} aria-label="Mở cuốn sổ kỷ niệm"><span className="tet-code-cover-ribbon" aria-hidden="true" /><span className="tet-code-cover-ornament" aria-hidden="true">✦</span><strong>Kỷ niệm của chúng ta</strong><small>Chạm để mở</small></motion.button></motion.section>}

      {isBookOpen && !isDecisionVisible && <section className="tet-code-reader" aria-label="Đọc cuốn sổ kỷ niệm"><header className="tet-code-reader-heading"><p>{currentPage.eyebrow}</p><h1>{currentPage.title}</h1></header><AnimatePresence mode="wait">{selectedPhoto !== null ? <PhotoPreview key={`photo-${selectedPhoto}`} photo={selectedPhoto} onClose={() => setSelectedPhoto(null)} /> : <motion.div key={currentPage.id} className="tet-code-page-turn" initial={reduceMotion ? false : { opacity: 0, rotateY: -18, x: 26 }} animate={{ opacity: 1, rotateY: 0, x: 0 }} exit={{ opacity: 0, rotateY: 16, x: -26 }} transition={{ duration: reduceMotion ? 0.12 : 0.54, ease: [0.22, 1, 0.36, 1] }}>{currentPage.photos ? <PhotoSpread page={currentPage} onSelect={setSelectedPhoto} /> : currentPage.id === "video" ? <VideoSpread /> : <PinSpread onOpen={() => setIsDecisionVisible(true)} />}</motion.div>}</AnimatePresence>{selectedPhoto === null && <nav className="tet-code-reader-controls" aria-label="Lật trang"><button type="button" onClick={previousPage} disabled={pageIndex === 0}><CaretLeft size={18} weight="bold" />Trang trước</button><span>{pageIndex + 1} / {bookPages.length}</span><button type="button" onClick={nextPage} disabled={pageIndex === bookPages.length - 1}>Trang sau<CaretRight size={18} weight="bold" /></button></nav>}</section>}

      <AnimatePresence mode="wait">
        {isDecisionVisible && !chosenRoad && <motion.section key="question" className="tet-decision" initial={reduceMotion ? false : { opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduceMotion ? 0.14 : 0.86, ease: [0.22, 1, 0.36, 1] }}><p className="scene-eyebrow">Sau những ngày rất vui</p><h1>Hai đứa có thể hiểu và chấp nhận nhau không?</h1><div className="tet-road-choices">{roads.map((road) => <button key={road.id} type="button" className="tet-road-choice" onClick={() => setChosenRoad(road.id)}><span>{road.title}</span><small>{road.description}</small></button>)}</div></motion.section>}
        {isDecisionVisible && chosenRoad && <motion.section key="subtitle" className="tet-decision-subtitle" initial={reduceMotion ? false : { opacity: 0, y: 28 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: reduceMotion ? 0.14 : 0.72, ease: [0.22, 1, 0.36, 1] }}><p className="tet-decision-chosen">{chosenRoadData?.title}</p><p className="tet-decision-copy">Tình yêu không phải lúc nào cũng là tìm được một người giống mình. Đôi khi, đó là học cách hiểu và chấp nhận một người khác mình.</p><p className="tet-decision-copy tet-decision-copy-secondary">Cảm ơn em vì dù có những lúc rất khó khăn, em vẫn chọn ở lại.</p><button type="button" className="tet-decision-next" onClick={onComplete}>Đi chặng tiếp theo <CaretRight size={18} weight="bold" /></button></motion.section>}      </AnimatePresence>
    </section></>
  );
}